#!/bin/bash

[ -z "$DIYkit" ] && export DIYkit=$HOME/.DIYkit
. $DIYkit/DIYkit.sh

(
cd $DIYkit

if [ $(uname -m) == "x86_64" -a ! -L lib64 ] ; then
    mkdir -p lib
    if [ -e lib64 ] ; then
        echo "ERROR: $NNlab_path/lib64/ is not a link to lib/."
        echo "Please move all of its contents to lib/ and replace it by a symbolic link"
    fi
    ln -s lib lib64
fi

CMD=$1 ; shift

case $CMD in
install)
    bash ./$1.diy
    ;;
depend)
    DEPENDENCY_ONLY=true bash ./$1.diy
    ;;
avail)
    for pkg in $( ( for x in *.diy ; do basename $x .diy ; done ) | sort ) ; do
        echo "$(printf "%-15s " $pkg)$(head -n 1 $pkg.diy | grep "^#")"
    done
    ;;
update)
    git pull
    ;;
*)
    exec $CMD "$*"
    ;;
esac
)
