#!/bin/bash

[ -z "$DIYkit" ] && export DIYkit=$HOME/.DIYkit
. $DIYkit/DIYkit.sh

(
cd $DIYkit

if [ $(uname -m) == "x86_64" -a ! -L lib64 ] ; then
    mkdir -p lib
    if [ -e lib64 ] ; then
        echo "ERROR: $DIYkit/lib64/ is not a link to lib/."
        echo "Please move all of its contents to lib/ and replace it by a symbolic link"
    fi
    ln -s lib lib64
fi

CMD=$1 ; shift

case $CMD in
install)
    bash ./$1.diy
    ;;
avail)
    for pkg in $( ( for x in *.diy ; do basename $x .diy ; done ) | sort ) ; do
        NAME=$pkg
        VERSION_INSTALLED=$(DIY_GET=INSTALLED bash $pkg.diy)
        VERSION_AVAILABLE=$(DIY_GET=VERSION bash $pkg.diy)
        COMMENT=$(grep "# DIYkit package:" $pkg.diy | sed "s/.*: //")
        printf "%-20s %-15s %-15s %s\n" "$NAME" "$VERSION_INSTALLED" "$VERSION_AVAILABLE" "$COMMENT"
    done
    ;;
update)
    git pull
    ;;
*)
    echo "DIYkit ERROR: unknown command '$CMD'"
    ;;
esac
)
