#!/bin/bash

. ~/NNlab/NNlab.sh

(
cd $NNlab_path

if [ $# -eq 0 ] ; then
    if [ "`basename -- $0`" == "NNlab" ] ; then
        exec bash
    fi
else

    CMD=$1
    shift

    case $CMD in
    install)
        bash ./$1.sh
        ;;
    depend)
        DEPENDENCY_ONLY=true bash ./$1.nnl
        ;;
    avail)
        ( for x in *.nnl ; do basename $x .nnl ; done ) | sort
        ;;
    update)
        git pull
        ;;
    *)
        exec $CMD "$*"
        ;;
    esac
fi
)
