#!/bin/bash

. ~/NNlab/NNlab.sh

(
cd $NNlab_path

if [ $# -eq 0 ] ; then
    if [ "`basename -- $0`" == "NNlab" ] ; then
        exec bash
    fi
else

    CMD=$1
    shift

    case $CMD in
    install)
        bash ./$1.sh
        ;;
    update)
        git pull
        ;;
    *)
        exec $1 "$*"
        ;;
    esac
fi
)
